import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { commandCapabilities } from "../src/core/capabilities";
import type { CommandCapability } from "../src/types/ZplDocument";

const target = resolve("docs/CONFORMANCE.md");

function semanticEvidence(capability: CommandCapability): string {
  if (capability.status === "unsupported") return "`documentParser.test.ts`";
  if (capability.category === "barcode") {
    return "`interpreter.test.ts`, `extendedBarcodes.test.ts`, specialized encoder suites";
  }
  if (capability.category === "graphic") {
    return "`graphicDecoder.test.ts`, `renderingCommands.test.ts`";
  }
  if (capability.category === "text") {
    return "`interpreter.test.ts`, `rendering.test.ts`";
  }
  if (capability.category === "storage") {
    return "`jobRenderer.test.ts`, `graphicDecoder.test.ts`";
  }
  return "`documentParser.test.ts`, `interpreter.test.ts`, `renderingCommands.test.ts`";
}

function rasterEvidence(capability: CommandCapability): string {
  if (capability.status === "unsupported") return "—";
  if (capability.effect === "job") return "`jobRenderer.test.ts`, `representativeLabels.test.ts`";
  if (capability.category === "barcode") {
    return "`barcodeConformance.test.ts`, `extendedBarcodes.test.ts`, independent ZXing decode";
  }
  if (capability.category === "graphic") return "`renderingCommands.test.ts`, `representativeLabels.test.ts`";
  return "`rendering.test.ts`, `renderingCommands.test.ts`, `representativeLabels.test.ts`";
}

const supported = commandCapabilities.filter(({ status }) => status === "supported");
const partial = commandCapabilities.filter(({ status }) => status === "partial");
const deviceOnly = commandCapabilities.filter(({ status }) => status === "non-rendering");
const unsupported = commandCapabilities.filter(({ status }) => status === "unsupported");

const rows = [...supported, ...partial, ...unsupported].map((capability) =>
  `| \`${capability.canonical}\` | ${capability.status} | ${capability.limitations?.join(" ") ?? "—"} | \`commandConformance.test.ts\` + \`documentParser.test.ts\` | ${semanticEvidence(capability)} | ${rasterEvidence(capability)} |`
);
const output = `<!-- Generated by scripts/generate-conformance-docs.ts. Do not edit. -->
# Command conformance evidence

The October 10, 2025 renderer profile contains ${supported.length} supported, ${partial.length} partial, and ${unsupported.length} unsupported rendering/job commands. Partial and unsupported limitations are listed in the table. \`commandConformance.test.ts\` is an identity and capability-regression smoke test; it does not by itself prove semantic dispatch. The remaining columns point to the deeper category and command-specific suites that exercise semantic behavior, persistence, and raster output. Representative output is pinned with raster hashes, and barcode families are decoded by the independent test-only ZXing implementation where supported by that decoder.

All ${deviceOnly.length} device-only commands are parsed by full identity and rendered against a blank control label in \`commandConformance.test.ts\`. Their packed rasters must be byte-identical to the control while returning \`NON_RENDERING_COMMAND\`.

| Command | Status | Limitations | Identity smoke | Semantic evidence | Raster evidence |
| :--- | :--- | :--- | :--- | :--- | :--- |
${rows.join("\n")}
`;

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(target, "utf8"); } catch {}
  if (current !== output) {
    console.error("docs/CONFORMANCE.md is stale. Run pnpm docs:conformance.");
    process.exitCode = 1;
  }
} else {
  mkdirSync(resolve("docs"), { recursive: true });
  writeFileSync(target, output);
}
