import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { commandCapabilities } from "../src/core/capabilities";

const target = resolve("docs/COMMAND_SUPPORT.md");
const guide =
  "https://docs.zebra.com/us/en/printers/software/zpl-pg/zpl-ii,-zbi-2,-set-get-do,-mirror,-wml-programming-guide.html";
const commandIndex =
  "https://docs.zebra.com/us/en/printers/software/zpl-pg/c-zpl-zpl-commands.html";

function cell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
}

const rows = commandCapabilities.map((capability) => {
  const limitations = capability.limitations?.join(" ") || "—";
  return `| \`${capability.canonical}\` | ${cell(capability.name)} | ${capability.category} | ${capability.effect} | ${capability.scope} | **${capability.status}** | ${cell(limitations)} | [reference](${capability.reference}) |`;
});

const supportedCount = commandCapabilities.filter(
  ({ status }) => status === "supported"
).length;
const nonRenderingCount = commandCapabilities.filter(
  ({ status }) => status === "non-rendering"
).length;

const output = `<!-- Generated by scripts/generate-support-docs.ts. Do not edit. -->
# ZPL II 2025 command support

This table is generated from the runtime command catalog. The renderer is pinned to Zebra's [current programming guide](${guide}) and [command index](${commandIndex}).

This profile contains **${supportedCount} supported** rendering/job commands and **${nonRenderingCount} recognized non-rendering** device commands. It has no partial or unsupported entries.

Support levels in this table:

- **supported**: rendered or interpreted for the complete label-rendering profile.
- **non-rendering**: recognized printer/device behavior with no label-raster effect.

| Command | Name | Category | Effect | Scope | Status | Limitations | Zebra |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
${rows.join("\n")}
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    // Report the same deterministic mismatch as stale generated content.
  }
  if (current !== output) {
    console.error("docs/COMMAND_SUPPORT.md is stale. Run pnpm docs:support.");
    process.exitCode = 1;
  }
} else {
  mkdirSync(resolve("docs"), { recursive: true });
  writeFileSync(target, output);
}
