// Device-conformance masks captured from a ZD410-203dpi ZPL preview at
// ^GSN,60,60. Each mask is an 80-by-60, MSB-first monochrome cell. The
// additional horizontal cell space preserves the documented UL/CSA glyph
// overhang while allowing deterministic nearest-dot scaling.
const SYMBOL_BASE64: Readonly<Record<string, string>> = Object.freeze({
  A: "AAH//AAAAAAAAAAB//wAAAAAAAAAAf/8AAAAAAAAAH////AAAAAAAAB////wAAAAAAAAf///8AAAAAAAA/4AA/4AAAAAAAP+AAP+AAAAAAAD/gAD/gAAAAAAH4AAAA/AAAAAAB+AAAAPwAAAAAAfgAAAD8AAAAAAH4H//A/AAAAAAB+B//wPwAAAAAAfgf/8D8AAAAAA/AH//4H4AAAAAPwB//+B+AAAAAD8Af//gfgAAAAA/AH4H4H4AAAAAPwB+B+B+AAAAAD8AfgfgfgAAAAA/AH//AH4AAAAAPwB//wB+AAAAAD8Af/8AfgAAAAA/AH//AH4AAAAAPwB//wB+AAAAAD8Af/8AfgAAAAA/AH4/4H4AAAAAPwB+P+B+AAAAAD8Afj/gfgAAAAAH4H4H4/AAAAAAB+B+B+PwAAAAAAfgfgfj8AAAAAAH4AAAA/AAAAAAB+AAAAPwAAAAAAfgAAAD8AAAAAAA/4AA/4AAAAAAAP+AAP+AAAAAAAD/gAD/gAAAAAAAH////AAAAAAAAB////wAAAAAAAAf///8AAAAAAAAAH//AAAAAAAAAAB//wAAAAAAAAAAf/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  B: "AAH//AAAAAAAAAAB//wAAAAAAAAAAf/8AAAAAAAAAH////AAAAAAAAB////wAAAAAAAAf///8AAAAAAAA/4AA/4AAAAAAAP+AAP+AAAAAAAD/gAD/gAAAAAAH4AAAA/AAAAAAB+AAAAPwAAAAAAfgAAAD8AAAAAAH4A//A/AAAAAAB+AP/wPwAAAAAAfgD/8D8AAAAAA/AH//AH4AAAAAPwB//wB+AAAAAD8Af/8AfgAAAAA/A/AAAH4AAAAAPwPwAAB+AAAAAD8D8AAAfgAAAAA/A/AAAH4AAAAAPwPwAAB+AAAAAD8D8AAAfgAAAAA/A/AAAH4AAAAAPwPwAAB+AAAAAD8D8AAAfgAAAAA/AH//AH4AAAAAPwB//wB+AAAAAD8Af/8AfgAAAAAH4A//A/AAAAAAB+AP/wPwAAAAAAfgD/8D8AAAAAAH4AAAA/AAAAAAB+AAAAPwAAAAAAfgAAAD8AAAAAAA/4AA/4AAAAAAAP+AAP+AAAAAAAD/gAD/gAAAAAAAH////AAAAAAAAB////wAAAAAAAAf///8AAAAAAAAAH//AAAAAAAAAAB//wAAAAAAAAAAf/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  C: "////A/AAH4AAAP///wPwAB+AAAD///8D8AAfgAAA////A/4A/4AAAP///wP+AP+AAAD///8D/gD/gAAAAH4AA//H/4AAAAB+AAP/x/+AAAAAfgAD/8f/gAAAAH4AA////4AAAAB+AAP///+AAAAAfgAD////gAAAAH4AA/H/H4AAAAB+AAPx/x+AAAAAfgAD8f8fgAAAAH4AA/A4H4AAAAB+AAPwOB+AAAAAfgAD8DgfgAAAAH4AA/AAH4AAAAB+AAPwAB+AAAAAfgAD8AAfgAAAAH4AA/AAH4AAAAB+AAPwAB+AAAAAfgAD8AAfgAAAAH4AA/AAH4AAAAB+AAPwAB+AAAAAfgAD8AAfgAAAAH4AA/AAH4AAAAB+AAPwAB+AAAAAfgAD8AAfgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  D: "AAAH////4AAAAAAAB////+AAAAAAAAf////gAAAAAAH//////4AAAAAB//////+AAAAAAf//////gAAAAA//AAAA//AAAAAP/wAAAP/wAAAAD/8AAAD/8AAAAH/AAAAAA/4AAAB/wAAAAAP+AAAAf8AAAAAD/gAAA/4/A/AAAH/AAAP+PwPwAAB/wAAD/j8D8AAAf8AAA/A/A/AAAA/AAAPwPwPwAAAPwAAD8D8D8AAAD8AAH4A/A/AAAAH4AB+APwPwAAAB+AAfgD8D8AAAAfgAH4A/A/AAAAH4AB+APwPwAAAB+AAfgD8D8AAAAfgA/AA/A/AAAAA/APwAPwPwAAAAPwD8AD8D8AAAAD8A/AA/A/H4AAA/APwAPwPx+AAAPwD8AD8D8fgAAD8A/AA/A/H4AAA/APwAPwPx+AAAPwD8AD8D8fgAAD8A/AA/A/H4AAA/APwAPwPx+AAAPwD8AD8D8fgAAD8A/AA///H4AAA/APwAP//x+AAAPwD8AD//8fgAAD8A/AAH/4H4AAA/APwAB/+B+AAAPwD8AAf/gfgAAD8A/AAAAAH4AAA/APwAAAAB+AAAPwD8AAAAAfgAAD8A/AAH/AH4AAA/APwAB/wB+AAAPwD8AAf8AfgAAD8AH4A4A4H4AAH4AB+AOAOB+AAB+AAfgDgDgfgAAfgAH4HH/HH//AH4AB+Bx/xx//wB+AAfgcf8cf/8AfgAA/HHHHH//A/AAAPxxxxx//wPwAAD8ccccf/8D8AAA//H4HAAAH/AAAP/x+BwAAB/wAAD/8fgcAAAf8AA",
  E: "AAAA////AAAAAAAAAP///wAAAAAAAAD///8AAAAAAAA//////AAAAAAAP/////wAAAAAAD/////8AAAAAA//4AAH//AAAAAP/+AAB//wAAAAD//gAAf/8AAAAH/4AAAAH/4AAAB/+AAAAB/+AAAAf/gAAAAf/gAAA//A/4H4A//AAAP/wP+B+AP/wAAD/8D/gfgD/8AAH/4H/4H/AH4AAB/+B/+B/wB+AAAf/gf/gf8AfgAAH/A//4H/4AAAAB/wP/+B/+AAAAAf8D//gf/gAAAA/4H/H4H//AAAAP+B/x+B//wAAAD/gf8fgf/8AAAA/4H4H4H4/4AAAP+B+B+B+P+AAAD/gfgfgfj/gAAA/AH/AAH4H4AAAPwB/wAB+B+AAAD8Af8AAfgfgAAA/AA/4AH4H/AAAPwAP+AB+B/wAAD8AD/gAfgf8AAA/AAH/AH///AAAPwAB/wB///wAAD8AAf8Af//8AAA/AAA/4H///AAAPwAAP+B///wAAD8AAD/gf//8AAA/AAAH4H4A/AAAPwAAB+B+APwAAD8AAAfgfgD8AAA/AH4H4H4H/AAAPwB+B+B+B/wAAD8Afgfgfgf8AAA/4H/H4H4H4AAAP+B/x+B+B+AAAD/gf8fgfgfgAAA/4A//4H4AAAAAP+AP/+B+AAAAAD/gD//gfgAAAAAH/AH/4H4AAAAAB/wB/+B+AAAAAAf8Af/gfgAAAAAH/4A/4H4AH4AAB/+AP+B+AB+AAAf/gD/gfgAfgAAA//AAAAAA//AAAP/wAAAAAP/wAAD/8AAAAAD/8AA",
});

const alphabet =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
const decoded = new Map<string, Uint8Array>();

export function zebraGraphicSymbolData(code: string): Uint8Array | undefined {
  const normalized = code.toUpperCase();
  const encoded = SYMBOL_BASE64[normalized];
  if (!encoded) return undefined;
  const existing = decoded.get(normalized);
  if (existing) return existing;
  const bytes: number[] = [];
  let value = 0;
  let bits = 0;
  for (const character of encoded.replace(/=+$/, "")) {
    value = (value << 6) | alphabet.indexOf(character);
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      bytes.push((value >> bits) & 0xff);
    }
  }
  const data = Uint8Array.from(bytes);
  decoded.set(normalized, data);
  return data;
}

export const ZEBRA_GRAPHIC_SYMBOL_WIDTH = 80;
export const ZEBRA_GRAPHIC_SYMBOL_HEIGHT = 60;
export const ZEBRA_GRAPHIC_SYMBOL_BYTES_PER_ROW = 10;
